version: '3'
services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 292003
      MYSQL_DATABASE: workmanagement
      MYSQL_USER: quangduong
      MYSQL_PASSWORD: 292003
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - es_network

  spring-boot-app:
    container_name: work-management-backend
    restart: always
    build: .
    ports:
      - 8081:8081
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: workmanagement
      DB_USER: quangduong
      DB_PASSWORD: 292003
    networks:
      - es_network

volumes:
  mysql_data:

networks:
  es_network:
    driver: bridge
